[2024-08-04T06:59:14.658+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T06:59:14.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process.data_quality_check.data_column_validation_dim_customers scheduled__2024-08-03T00:00:00+00:00 [queued]>
[2024-08-04T06:59:14.702+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process.data_quality_check.data_column_validation_dim_customers scheduled__2024-08-03T00:00:00+00:00 [queued]>
[2024-08-04T06:59:14.703+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-04T06:59:14.717+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLColumnCheckOperator): data_quality_check.data_column_validation_dim_customers> on 2024-08-03 00:00:00+00:00
[2024-08-04T06:59:14.724+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_process', 'data_quality_check.data_column_validation_dim_customers', 'scheduled__2024-08-03T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpxgob6fwe']
[2024-08-04T06:59:14.726+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask data_quality_check.data_column_validation_dim_customers
[2024-08-04T06:59:14.728+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=177) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-04T06:59:14.729+0000] {standard_task_runner.py:63} INFO - Started process 194 to run task
[2024-08-04T06:59:14.779+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_process.data_quality_check.data_column_validation_dim_customers scheduled__2024-08-03T00:00:00+00:00 [running]> on host 28819dc9564a
[2024-08-04T06:59:14.862+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ztamnaja' AIRFLOW_CTX_DAG_ID='etl_process' AIRFLOW_CTX_TASK_ID='data_quality_check.data_column_validation_dim_customers' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-03T00:00:00+00:00'
[2024-08-04T06:59:14.863+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T06:59:14.883+0000] {base.py:84} INFO - Using connection ID 'destination_db_conn' for task execution.
[2024-08-04T06:59:14.951+0000] {base.py:84} INFO - Using connection ID 'destination_db_conn' for task execution.
[2024-08-04T06:59:14.956+0000] {sql.py:487} INFO - Running statement: SELECT col_name, check_type, check_result FROM (
        SELECT 'customer_id' AS col_name, 'null_check' AS check_type, customer_id_null_check AS check_result
        FROM (SELECT SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END) AS customer_id_null_check FROM dim_customers ) AS sq
    ) AS check_columns, parameters: None
[2024-08-04T06:59:14.958+0000] {sql.py:496} INFO - Rows affected: 1
[2024-08-04T06:59:14.959+0000] {sql.py:479} INFO - Record: [('customer_id', 'null_check', 0)]
[2024-08-04T06:59:14.960+0000] {sql.py:502} INFO - All tests have passed
[2024-08-04T06:59:14.960+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T06:59:14.970+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_process, task_id=data_quality_check.data_column_validation_dim_customers, run_id=scheduled__2024-08-03T00:00:00+00:00, execution_date=20240803T000000, start_date=20240804T065914, end_date=20240804T065914
[2024-08-04T06:59:15.024+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-04T06:59:15.041+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-04T06:59:15.044+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
